[workspace]
name = "phono-core-env"
version = "0.1.1"
description = "phono core compile environment"
channels = ["conda-forge"]
platforms = [
    { name = "linux-glibc228", platform = "linux-64", glibc = "2.28" },
    { name = "osx-arm64", platform = "osx-arm64" },
    { name = "win-64", platform = "win-64" }
]

[dependencies]
python = ">=3.13,<3.14"
ninja = "*"
cmake = "*"
pip = "*"

c-compiler = "*"
cxx-compiler = "*"

[pypi-dependencies]
torch = "*"
executorch = "*"

[tasks]
setup = "test -d third_party/executorch/.git || git clone --recursive --depth 1 https://github.com/pytorch/executorch third_party/executorch"
format = "black . && isort ."
lint = "flake8 . && mypy ."
config = "cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release $CMAKE_ARGS"
build = "cmake --build build"

[environments]
default = { features = [], solve-group = "default" }