#!/usr/bin/env python3
"""Code-generate a native C++ table for the zh2Hans (Traditional -> Simplified)
conversion rules.

Reads the slimmed OpenCC-style dictionary ``res/zh2hans.json`` (a JSON object
holding the ``zh2Hans`` rule map) and emits ``src/gen/zh2hansdict.h``:

  * ``kRules``          - every rule as ``{u32 codepoints, utf-8 bytes}`` pair.
  * ``kFirstCpIndex``   - rules grouped by first code point, each group sorted
                          by key length (in code points) descending so that the
                          first matching rule inside a group is always the
                          longest match (maximal-munch).

The header is meant to be regenerated at CMake configure time via
``execute_process``; it is also runnable standalone::

    python codegen/zh2hans_codegen.py --input res/zh2hans.json --output src/gen/zh2hansdict.h
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Dict, List, Tuple


def cxx_utf8_literal(text: str) -> str:
    """Emit a UTF-8 string as a portable byte-escaped C++ string literal.

    Every byte is written as its own ``\\xNN`` escape; because each escape is
    immediately followed by another backslash or the closing quote, no ``\\x``
    escape can accidentally consume hex digits that belong to the next byte.
    """
    return '"' + "".join("\\x%02X" % b for b in text.encode("utf-8")) + '"'


def cxx_u32_string(cps: List[int]) -> str:
    """Emit a sequence of code points as a single u32 literal.

    Hex escapes are self-delimiting here because every escape is followed by
    another backslash or the closing quote, never a literal hex digit.
    """
    return 'U"' + "".join("\\x%04X" % cp if cp <= 0xFFFF else "\\x%05X" % cp for cp in cps) + '"'


def build_index(rules: List[Tuple[str, str]]) -> Tuple[
    List[Tuple[int, List[Tuple[str, str]]]], int]:
    """Group rules by first code point, sort groups by cp, and sort each
    group's rules by key length (in code points) descending.

    Returns ([(first_cp, [rules...]), ...], total_rule_count).
    """
    groups: Dict[int, List[Tuple[str, str]]] = {}
    for key, value in rules:
        if not key:
            raise ValueError("empty rule key")
        first_cp = ord(key[0])
        groups.setdefault(first_cp, []).append((key, value))

    ordered: List[Tuple[int, List[Tuple[str, str]]]] = []
    for cp in sorted(groups):
        members = groups[cp]
        members.sort(key=lambda kv: len(kv[0]), reverse=True)
        ordered.append((cp, members))

    total = sum(len(members) for _, members in ordered)
    return ordered, total


def render_header(groups: List[Tuple[int, List[Tuple[str, str]]]], total: int) -> str:
    lines: List[str] = []
    lines.append("// Generated by codegen/zh2hans_codegen.py from res/zh2hans.json.")
    lines.append("// DO NOT EDIT BY HAND.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("#include <string_view>")
    lines.append("")
    lines.append("namespace phono {")
    lines.append("namespace algo {")
    lines.append("namespace zh2hans {")
    lines.append("")
    lines.append("struct Rule {")
    lines.append("    std::u32string_view from;  // matching key, code points")
    lines.append("    std::string_view to;       // replacement, UTF-8 bytes")
    lines.append("};")
    lines.append("")
    lines.append("struct FirstCpEntry {")
    lines.append("    std::uint32_t cp;")
    lines.append("    std::size_t begin;")
    lines.append("    std::size_t end;")
    lines.append("};")
    lines.append("")
    lines.append("// kRules within each FirstCpEntry group are ordered by key length")
    lines.append("// (in code points) descending, so the first prefix match inside a")
    lines.append("// group is the longest match.")
    lines.append(f"inline constexpr std::array<Rule, {total}> kRules = {{")
    lines.append("    {")
    cursor = 0
    for cp, members in groups:
        for key, value in members:
            cps = [ord(c) for c in key]
            comment = "  // " + key if len(key) <= 6 else "  // " + key
            lines.append(
                f"        Rule{{{cxx_u32_string(cps)}, {cxx_utf8_literal(value)}}},{comment}"
            )
            cursor += 1
    assert cursor == total, "rule count mismatch"
    lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr std::array<FirstCpEntry, {len(groups)}> kFirstCpIndex = {{")
    lines.append("    {")
    cursor = 0
    for cp, members in groups:
        end = cursor + len(members)
        lines.append(f"        FirstCpEntry{{0x{cp:04X}, {cursor}, {end}}},")
        cursor = end
    lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr std::size_t kRuleCount = {total};")
    lines.append("")
    lines.append("}  // namespace zh2hans")
    lines.append("}  // namespace algo")
    lines.append("}  // namespace phono")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="path to res/zh2hans.json")
    parser.add_argument("--output", required=True, help="path to src/gen/zh2hansdict.h")
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict) or "zh2Hans" not in data:
        raise ValueError(
            "expected a JSON object with a 'zh2Hans' rule map, got: %r" % (type(data),)
        )

    rules = [(str(k), str(v)) for k, v in data["zh2Hans"].items()]
    groups, total = build_index(rules)

    header = render_header(groups, total)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(header)

    print(
        f"zh2hans codegen: {total} rules, {len(groups)} first-cp groups -> {args.output}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
